# Merci de concentrer votre attention, lors de la compilation, sur morceau_methode5.c car c'est le fichier correspondant surtout aux attentes strictes des professeurs

# Pour le compiler, merci d'essayer gcc morceau_methode5.c -lm -lgsl  en se plaçant bien dans le dossier ProcessPart (tant que le Make n'est pas fonctionnel)

all: morceau_methode5.c

morceau_methode5: a.out
    gcc morceau_methode5.c -lm -lgsl
